sudo: false

language: node_js

services:
  - rabbitmq

matrix:
  include:
    - node_js: "9"

    - node_js: "8"

install:
  - npm install
  - if [ -n "$NPM_INSTALL_PACKAGES" ]; then npm install $NPM_INSTALL_PACKAGES; fi

script:
  - npm run ${NPM_RUN_SCRIPT:-test} -- $MOCHA_ARGS
